web/ask/ask/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('qa.urls', namespace='qa')),
                       )

web/ask/qa/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('qa.views',
                       url(r'^$', 'index', name='index'),
                       url(r'^popular/$', 'popular', name='popular'),
                       url(r'^question/(?P<slug>\w+)/$', 'question', name='question'),
                       url(r'^ask/$', 'ask', name='ask'),
                       url(r'^answer/$', 'answer', name='answer'),
                       url(r'^signup/$', 'signup', name='signup'),
                       url(r'^login/$', 'login', name='login'),
                       )

web/ask/qa/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    added_at = models.DateField(default=timezone.now(), null=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    likes = models.ManyToManyField(User, related_name='likes')

    def __unicode__(self):
        return self.title

    def get_url(self):
        return reverse('qa:question', kwargs={'slug': self.pk})


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateField(default=timezone.now(), null=True)
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.text

    def get_url(self):
        return self.question.get_url()

web/ask/qa/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from qa.models import Question, Answer


class AskForm(forms.Form):
    title = forms.CharField(min_length=1, max_length=255)
    text = forms.CharField(min_length=1, widget=forms.Textarea)

    def save(self):
        question = Question(**self.cleaned_data)
        question.author_id = self._user.id
        question.save()
        return question


class AnswerForm(forms.Form):
    text = forms.CharField(min_length=1, widget=forms.Textarea)
    question = forms.IntegerField(widget=forms.HiddenInput)

    def clean_question(self):
        question_id = self.cleaned_data['question']
        try:
            question = Question.objects.get(pk=question_id)
        except Question.DoesNotExist:
            raise forms.ValidationError('Question %s not found' % id)
        return question

    def save(self):
        answer = Answer(**self.cleaned_data)
        answer.author_id = self._user.id
        answer.save()
        return answer


class LoginForm(forms.Form):
    username = forms.CharField(min_length=1, max_length=255, required=True)
    password = forms.CharField(min_length=1, max_length=255, widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError('Authorization failed')
        self.cleaned_data['user'] = user
        return self.cleaned_data

    def save(self):
        return self.cleaned_data['user']


class SignupForm(LoginForm):
    email = forms.EmailField(min_length=1, max_length=255, required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" already used' % username)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" already used' % email)

    def clean(self):
        if self._errors:
            raise forms.ValidationError('Registration failed')
        User.objects.create_user(**self.cleaned_data)
        return super(SignupForm, self).clean()

web/ask/qa/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import auth

from qa.models import Question
from qa.forms import AskForm, AnswerForm, LoginForm, SignupForm


def paginate(request, lines, limit=10):
    paginator = Paginator(lines, limit)
    page = request.GET.get('page', 1)
    try:
        return paginator.page(page)
    except PageNotAnInteger:
        raise Http404
    except EmptyPage:
        return paginator.page(paginator.num_pages)


@require_GET
def index(request, *args, **kwds):
    last_questions = Question.objects.order_by('-id')
    context = {'questions': paginate(request, last_questions)}
    return render(request, 'index.html', context)


@require_GET
def popular(request, *args, **kwds):
    popular_questions = Question.objects.order_by('-rating')
    context = {'questions': paginate(request, popular_questions)}
    return render(request, 'list.html', context)


def question(request, slug):
    if request.method == 'POST':
        return answer(request)
    else:
        try:
            id = int(slug)
        except ValueError:
            raise Http404
        question = get_object_or_404(Question, pk=id)
        return render(request, 'single.html', {'question': question})


def ask(request):
    return _post(request, AskForm, 'ask.html')


def answer(request):
    return _post(request, AnswerForm, 'answer.html')


def _post(request, Form, template):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            form._user = request.user
            post = form.save()
            url = post.get_url()
            return HttpResponseRedirect(url)
    else:
        form = Form()
    return render(request, 'ask.html', {'form': form})


def signup(request):
    return _authorize(request, SignupForm, 'signup.html')


def login(request):
    return _authorize(request, LoginForm, 'login.html')


def _authorize(request, Form, template):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = Form()
    return render(request, template, {'form': form})

web/ask/qa/templates/answer.html
{% extends "form.html" %}

{% block post_url %}"{% url 'qa:answer' %}"{% endblock %}

web/ask/qa/templates/ask.html
{% extends "form.html" %}

{% block post_url %}"{% url 'qa:ask' %}"{% endblock %}

web/ask/qa/templates/form.html
{% for e in form.non_field_errors %}
<p>
    {{ e }}
</p>
{% endfor %}

<form method="post" action={% block post_url %}"/"{% endblock %}>
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button type="submit">Submit</button>
    </div>
</form>

web/ask/qa/templates/index.html
{% extends "list.html" %}

web/ask/qa/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Ask{% endblock %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

web/ask/qa/templates/list.html
{% extends "layout.html" %}

{% block content %}
{% if questions %}
<section>
    <ol>
    {% for question in questions %}
        <li><a href="{{ question.get_url }}">{{ question }}</a></li>
    {% endfor %}
    </ol>
</section>
<nav>
    <ul>
        {% for page in questions.paginator.page_range %}
        {% if page == questions.number %}
        <li class="active">
            {% else %}
        <li>
            {% endif %}
            <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>
{% else %}
<section>
    <p>No questions</p>
</section>
{% endif %}
{% endblock content %}

web/ask/qa/templates/login.html
{% extends "form.html" %}  

{% block post_url %}"{% url 'qa:login' %}"{% endblock %}

web/ask/qa/templates/signup.html
{% extends "form.html" %}  

{% block post_url %}"{% url 'qa:signup' %}"{% endblock %}

web/ask/qa/templates/single.html
{% extends "layout.html" %}

{% block content %}
<section>
    <h1>{{ question.title }}</h1>
    <div>{{ question.text }}</div>
</section>
<section>
    {% for answer in question.answer_set.all %}
    <div>{{ answer }}</div>
    {% endfor %}
</section>
<section>
    {% include "answer.html" %}
</section>
{% endblock content %}